version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  frontend:
    image: alexeyadavydov/foodgram_frontend:latest
    depends_on:
      - db
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ../frontend/:/app/result_build/


  backend:
    image: alexeyadavydov/foodgram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/static/
      - media:/app/media

  nginx:
    image: nginx:1.19.3
    ports:
      - "8090:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/ 
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media:/var/html/media/