# Generated by Django 3.2.16 on 2024-02-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240201_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
