# Generated by Django 3.2.16 on 2024-03-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subscribe_selfsubscribing_not_allowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
